# PageCMS Configuration for Meadowbrook Site

content:
  - name: pages
    label: Pages
    type: collection
    path: src/content/pages
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: string
        required: true
      - name: body
        label: Content
        type: text

media:
  input: public/images
  output: /images
