# PageCMS Configuration for Meadowbrook Site

# Collection for markdown pages
collections:
  - name: pages
    label: Pages
    folder: src/content/pages
    create: true
    delete: true
    slug: "{{slug}}"
    extension: md
    format: frontmatter
    fields:
      - name: title
        label: Title
        widget: string
        required: true
      - name: description
        label: Description
        widget: string
        required: true
      - name: body
        label: Content
        widget: markdown
        required: true

# Media storage configuration
media_folder: public/images
public_folder: /images

# Site metadata
site_url: https://example.com
display_url: https://example.com

# Editor configuration
editor:
  preview: true
